# Generated by Django 2.2.3 on 2019-08-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emxcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=16)),
                ('ifsc', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=20)),
                ('empno', models.CharField(max_length=12)),
                ('empsal', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmpBankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=16)),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emxcel.BankDetail')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emxcel.EmployeeDetail')),
            ],
        ),
    ]
