# Generated by Django 2.2.3 on 2019-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emxcel', '0002_bankdetail_empbankdetails_employeedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='eemail',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
